### ISSUE TITLE
cards.h not found

### ISSUE THREAD

**Issue by mr3188** [makespacemadrid/GLaDOS#2]
Al intentar compilar no encuentra cards.h 

¿pertenece a alguna librería o es un fuente que no está en el repo?

src\doorControlNode.h:8:19: fatal error: cards.h: No such file or directory

Miguel

**Comment by mr3188** [comment]
Parece ser la lista harcodedCards.
No tiene sentido subirlo al repositorio pero... ¿podemos subir un ejemplo para poder compilar?

Miguel

**Comment by successbyfailure** [comment]
Exacto, veo que ya has averiguado la cuestion. Por si todo falla hay una lista de tags autorizados que tengo en un fichero en el portatil. Ese no es para subirlo al repo por seguridad.
Con comentar la linea (o el ifdef que has puesto) deberia valer para poder compilar sin problema.

**Comment by mr3188** [comment]
Solucionado en #1
